### ISSUE TITLE
Skip commit if no test files are present

### ISSUE THREAD

**Issue by cboltt** [lydiachoi/test-percentage-visualizer#3]
At the beginning of a repo's history, there may not be any tests present. We should skip these commits without trying to install packages for a faster runtime.

**Comment by jregchiu** [comment]
Will try to work this into iterating over all commits when I have a chance. I'm guessing it would be something like checking for the presence of any files in a test/ directory in the repo?

**Comment by cboltt** [comment]
Exactly - detecting the presence of `*.test.js`/whatever other types of test files we support
