### ISSUE TITLE
Parse output.txt for useful information

### ISSUE THREAD

**Issue by cboltt** [lydiachoi/test-percentage-visualizer#4]
Output.txt simply contains all of our logs from running tests. We should parse through it to grab the important pieces of information needed for visualization.

**Comment by jregchiu** [comment]
Moving the discussion here from PR #5:

Jeremy commented:
> ... For #4 should we do the parsing as we're running the tests/coverage to only save the stuff we need to the output file, or do you think we should do it after?

Chris replied:
> ... Initial thought is that it makes sense to do it on the fly?
But then I think about the fact that the test suite, for whatever reason, may fail to run on a given commit. We wouldn’t have to handle this error if we’re simply parsing the file for successful test runs after the fact?

**Comment by xavierdelacruz** [comment]
As discussed @jregchiu earlier, is there a chance we could get the parsed output it in csv format? 

For example, a csv of data for the commit vs % coverage stacked bar chart would be something like this:

Commmit,Line Coverage %,Statement Coverage %, Branch Coverage %
1,90,85,31
2,99,70,90
3,80,80,80

**Comment by xavierdelacruz** [comment]
Saw what @cbolton97 submitted so far! Looking great!

I was wondering if we could have 2 csvs (stuff I need on my end):

1. Commit, Line Coverage, Branch Coverage, Statement Coverage and Function Coverage. If it's not too hard, could the values of the coverage have the % removed? 

2. Commit, Test Passed, Test Failed, Tests

If time permits, 
3. Commit, Overall coverage for each class (no need for specific coverage metrics). 
I plan on making an animated stream of data if time permits, which will look awesome!

Thank you again!

**Comment by cboltt** [comment]
@xavierdelacruz no easy (or possible?) way to get coverage per class, but we could get it per file?

**Comment by xavierdelacruz** [comment]
@cbolton97 per file would be wonderful! sorry, that's what I meant haha!

**Comment by cboltt** [comment]
@xavierdelacruz okay cool. I think that will be a separate issue since it's a bit more complicated haha.

**Comment by xavierdelacruz** [comment]
thank you!

**Comment by lydiachoi** [comment]
Completed
