### ISSUE TITLE
Instrument test files to collect memory information (and maybe wall clock info?)

### ISSUE THREAD

**Issue by jregchiu** [lydiachoi/test-percentage-visualizer#6]
Before ./get-coverage is run, we should run another script to instrument the test files with logging to print out memory usage (and maybe wall clock info to figure out runtime, if the test runner doesn't output that info already?)

I suspect it'll be something similar to [that exercise in class to instrument code](https://docs.google.com/presentation/d/1q-ThsuyZWp3e1VrwtAdmH0-H5YO5fjGEN7PcB6AL9nk/edit#slide=id.g45a35f27d1_0_51)

**Comment by jregchiu** [comment]
As a follow-up I think the time it takes to run the test suite is already output (at least for Chris' sample repo)

**Comment by lydiachoi** [comment]
@jregchiu can you clarify this issue?

**Comment by jregchiu** [comment]
@lydiachoi pretty sure we've covered this by collecting the heap and runtime?
