### ISSUE TITLE
Order of coverage types/bars in visualization

### ISSUE THREAD

**Issue by jregchiu** [lydiachoi/test-percentage-visualizer#9]
Is there an order to lay the bars beside one another that makes most sense when visualizing test coverage? Like most to least granular (line->statement->branch->function)

@xavierdelacruz and I talked about it and it's based off the order of columns in the CSV so relatively easy to change

**Comment by xavierdelacruz** [comment]
Seems like @cbolton97  already has done this :) Feel free to close it once confirmed!
